// generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx
import './home.<%= styleSheetExt %>';

import * as React from 'react';
import { Link } from 'react-router-dom';
import { Translate } from 'react-simlife';
import { connect } from 'react-redux';

import { getSession } from '../../reducers/authentication';

export interface IHomeProp {
  account: any;
  getSession: Function;
}

export interface IHomeState {
  currentUser: any;
}

export class Home extends React.Component<IHomeProp, IHomeState> {
  constructor(props) {
    super(props);
    this.state = {
      currentUser: props.account
    };
  }

  componentWillMount() {
    this.props.getSession();
  }

  componentWillReceiveProps(nextProps) {
    this.setState({
      currentUser: nextProps.account
    });
  }

  render() {
    const { currentUser } = this.state;

    return (
      <div className="row">
        <div className="col-md-9">
          <h2><Translate contentKey="home.title">Welcome, Java Simlife!</Translate></h2>
          <p className="lead"><Translate contentKey="home.subtitle">This is your homepage</Translate></p>
          {
            (currentUser && currentUser.login) ? (
              <div>
                <div className="alert alert-success">
                  <Translate contentKey="home.logged.message" interpolate={{ username: currentUser.login }}>You are logged in as user </Translate>
                </div>
              </div>
            ) : (
              <div>
                <div className="alert alert-warning">
                  <Translate contentKey="global.messages.info.authenticated.prefix">If you want to </Translate>
                  <Link to="/login" className="alert-link"><Translate contentKey="global.messages.info.authenticated.link">sign in</Translate></Link>
                  <Translate contentKey="global.messages.info.authenticated.suffix">, you can try the default accounts:
                  <br />- Administrator (login=&quot;admin&quot; and password=&quot;admin&quot;)
                  <br />- User (login=&quot;user&quot; and password=&quot;user&quot;).</Translate>
                </div>

                <div className="alert alert-warning">
                  <Translate contentKey="global.messages.info.register.noaccount">You do not have an account yet?</Translate>&nbsp;
                  <a className="alert-link"><Translate contentKey="global.messages.info.register.link">Register a new account</Translate></a>
                </div>
              </div>
            )
          }
          <p>
            <Translate contentKey="home.question">If you have any question on Simlife:</Translate>
          </p>

          <ul>
            <li>
              <a href="http://simlife.github.io/" target="_blank" rel="noopener noreferrer">
                <Translate contentKey="home.link.homepage">Simlife homepage</Translate>
              </a>
            </li>
            <li>
              <a href="http://stackoverflow.com/tags/simlife/info" target="_blank" rel="noopener noreferrer">
                <Translate contentKey="home.link.stackoverflow">Simlife on Stack Overflow</Translate>
              </a>
            </li>
            <li>
              <a href="https://github.com/simlife/simlife-bot/issues?state=open" target="_blank" rel="noopener noreferrer">
                <Translate contentKey="home.link.bugtracker">Simlife bug tracker</Translate>
              </a>
            </li>
            <li>
              <a href="https://gitter.im/simlife/simlife-bot" target="_blank" rel="noopener noreferrer">
                <Translate contentKey="home.link.chat">Simlife public chat room</Translate>
              </a>
            </li>
            <li>
              <a href="https://twitter.com/java_simlife" target="_blank" rel="noopener noreferrer">
                <Translate contentKey="home.link.follow">follow @java_simlife on Twitter</Translate>
              </a>
            </li>
          </ul>

          <p>
            <Translate contentKey="home.like">If you like Simlife, do not forget to give us a star on</Translate>
            <a href="https://github.com/simlife/simlife-bot" target="_blank" rel="noopener noreferrer">Github</a>!
          </p>
        </div>
        <div className="col-md-3 pad">
          <span className="simlife img-fluid rounded" />
        </div>
      </div>
    );
  }
}

const mapStateToProps = storeState => ({
  account: storeState.authentication.account,
  isAuthenticated: storeState.authentication.isAuthenticated
});

const mapDispatchToProps = { getSession };

export default connect(mapStateToProps, mapDispatchToProps)(Home);

// generators/client/templates/angular/src/main/webapp/app/home/_home.component.ts
<%#
 Copyright 2013-2018 the original author or authors from the Simlife project.

 This file is part of the Simlife project, see http://www.simlife.tech/
 for more information.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-%>
import { Component, OnInit } from '@angular/core';
<%_ if (authenticationType !== 'oauth2') { _%>
import { NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
<%_ } _%>
import { JhiEventManager } from 'ng-simlife';

import { Account, <% if (authenticationType !== 'oauth2') { %>LoginModalService<% } else { %>LoginService<% } %>, Principal } from '../shared';

@Component({
    selector: '<%= simPrefixDashed %>-home',
    templateUrl: './home.component.html',
    styleUrls: [
        <%_ if (useSass) { _%>
        'home.scss'
        <%_ } else { _%>
        'home.css'
        <%_ } _%>
    ]

})
export class HomeComponent implements OnInit {
    account: Account;
    <%_ if (authenticationType !== 'oauth2') { _%>
    modalRef: NgbModalRef;
    <%_ } _%>

    constructor(
        private principal: Principal,
        <%_ if (authenticationType !== 'oauth2') { _%>
        private loginModalService: LoginModalService,
        <%_ } else { _%>
        private loginService: LoginService,
        <%_ } _%>
        private eventManager: JhiEventManager
    ) {
    }

    ngOnInit() {
        this.principal.identity().then((account) => {
            this.account = account;
        });
        this.registerAuthenticationSuccess();
    }

    registerAuthenticationSuccess() {
        this.eventManager.subscribe('authenticationSuccess', (message) => {
            this.principal.identity().then((account) => {
                this.account = account;
            });
        });
    }

    isAuthenticated() {
        return this.principal.isAuthenticated();
    }

    login() {
        <%_ if (authenticationType !== 'oauth2') { _%>
        this.modalRef = this.loginModalService.open();
        <%_ } else { _%>
        this.loginService.login();
        <%_ }_%>
    }
}

<%#
 Copyright 2013-2018 the original author or authors from the Simlife project.

 This file is part of the Simlife project, see http://www.simlife.tech/
 for more information.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-%>
<div class="row">
    <div class="col-md-3">
        <span class="simlife img-fluid rounded"></span>
    </div>
    <div class="col-md-9">
        <h1 class="display-4" simTranslate="home.title">Welcome, Java Simlife!</h1>
        <p class="lead" simTranslate="home.subtitle">This is your homepage</p>

        <div [ngSwitch]="isAuthenticated()">
            <div class="alert alert-success" *ngSwitchCase="true">
                <span *ngIf="account" simTranslate="home.logged.message"
                    translateValues="{username: '{{account.login}}'}"> You are logged in as user "{{account.login}}". </span>
            </div>

            <div class="alert alert-warning" *ngSwitchCase="false">
                <span simTranslate="global.messages.info.authenticated.prefix">If you want to </span>
                <a class="alert-link" (click)="login()" simTranslate="global.messages.info.authenticated.link">sign in</a><span simTranslate="global.messages.info.authenticated.suffix">, you can try the default accounts:<br/>- Administrator (login="admin" and password="admin") <br/>- User (login="user" and password="user").</span>
            </div>
            <%_ if (authenticationType !== 'oauth2') { _%>
            <div class="alert alert-warning" *ngSwitchCase="false">
                <span simTranslate="global.messages.info.register.noaccount">You don't have an account yet?</span>
                <a class="alert-link" routerLink="register" simTranslate="global.messages.info.register.link">Register a new account</a>
            </div>
            <%_ } _%>
        </div>

        <p simTranslate="home.question">
            If you have any question on Simlife:
        </p>

        <ul>
            <li><a href="http://www.simlife.tech/" target="_blank" rel="noopener" simTranslate="home.link.homepage">Simlife homepage</a></li>
            <li><a href="http://stackoverflow.com/tags/simlife/info" target="_blank" rel="noopener" simTranslate="home.link.stackoverflow">Simlife on Stack Overflow</a></li>
            <li><a href="https://github.com/simlife/simlife-bot/issues?state=open" target="_blank" rel="noopener" simTranslate="home.link.bugtracker">Simlife bug tracker</a></li>
            <li><a href="https://gitter.im/simlife/simlife-bot" target="_blank" rel="noopener" simTranslate="home.link.chat">Simlife public chat room</a></li>
            <li><a href="https://twitter.com/java_simlife" target="_blank" rel="noopener" simTranslate="home.link.follow">follow @java_simlife on Twitter</a></li>
        </ul>

        <p>
            <span simTranslate="home.like">If you like Simlife, don't forget to give us a star on</span> <a href="https://github.com/simlife/simlife-bot" target="_blank" rel="noopener" simTranslate="home.github">GitHub</a>!
        </p>
    </div>
</div>
