// cli/demo/src/main/webapp/app/modules/administration/metrics/metrics.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Table, Progress, Col, Row, Button } from 'reactstrap';
import { TextFormat } from 'react-simlife';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_WHOLE_NUMBER_FORMAT, APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT } from 'app/config/constants';
import { systemMetrics, systemThreadDump } from '../administration.reducer';
import MetricsModal from './metrics-modal';
import { IRootState } from 'app/shared/reducers';

export interface IMetricsPageProps extends StateProps, DispatchProps {}

export interface IMetricsPageState {
  showModal: boolean;
}

export class MetricsPage extends React.Component<IMetricsPageProps, IMetricsPageState> {
  state: IMetricsPageState = {
    showModal: false
  };

  componentDidMount() {
    this.props.systemMetrics();
  }

  getMetrics = () => {
    if (!this.props.isFetching) {
      this.props.systemMetrics();
    }
  };

  getThreadDump = () => {
    this.props.systemThreadDump();
    this.setState({
      showModal: true
    });
  };

  handleClose = () => {
    this.setState({
      showModal: false
    });
  };

  filterNaN = input => (isNaN(input) ? 0 : input);

  getStats = metrics => {
    const stat = {
      servicesStats: {},
      cachesStats: {}
    };
    if (!this.props.isFetching && metrics && metrics.timers) {
      Object.keys(metrics.timers).forEach((key, indexNm) => {
        if (key.indexOf('web.rest') !== -1 || key.indexOf('service') !== -1) {
          stat.servicesStats[key] = metrics.timers[key];
        }
        if (key.indexOf('net.sf.ehcache.Cache') !== -1) {
          // remove gets or puts
          const index = key.lastIndexOf('.');
          const newKey = key.substr(0, index);
          // Keep the name of the domain
          stat.cachesStats[newKey] = {
            name: newKey,
            value: metrics.timers[key]
          };
        }
      });
    }
    return stat;
  };

  gaugeRow = (metrics, label: String, key) =>
    metrics.gauges[key] ? (
      <Row>
        <Col md="9">{label}</Col>
        <Col md="3" className="text-right">
          {metrics.gauges[key].value}
        </Col>
      </Row>
    ) : null;

  renderModal = () => <MetricsModal handleClose={this.handleClose} showModal={this.state.showModal} threadDump={this.props.threadDump} />;

  renderGauges = metrics => (
    <Row>
      <Col sm="12">
        <h3>JVM Metrics</h3>
        <Row>
          <Col md="4">
            <b>Memory</b>
            <p>
              <span>Total Memory</span> (
              <TextFormat value={metrics.gauges['jvm.memory.total.used'].value / 1048576} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
              M /{' '}
              <TextFormat value={metrics.gauges['jvm.memory.total.max'].value / 1048576} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
              M)
            </p>
            <Progress
              animated
              value={metrics.gauges['jvm.memory.total.used'].value}
              min="0"
              max={metrics.gauges['jvm.memory.total.max'].value}
              color="success"
            >
              <span>
                <TextFormat
                  value={(metrics.gauges['jvm.memory.total.used'].value * 100) / metrics.gauges['jvm.memory.total.max'].value}
                  type="number"
                  format={APP_WHOLE_NUMBER_FORMAT}
                />
                %
              </span>
            </Progress>
            <p>
              <span>Heap Memory</span> (
              <TextFormat value={metrics.gauges['jvm.memory.heap.used'].value / 1048576} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
              M /{' '}
              <TextFormat value={metrics.gauges['jvm.memory.heap.max'].value / 1048576} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
              M)
            </p>
            <Progress
              animated
              min="0"
              max={metrics.gauges['jvm.memory.heap.max'].value}
              value={metrics.gauges['jvm.memory.heap.used'].value}
              color="success"
            >
              <span>
                <TextFormat
                  value={(metrics.gauges['jvm.memory.heap.used'].value * 100) / metrics.gauges['jvm.memory.heap.max'].value}
                  type="number"
                  format={APP_WHOLE_NUMBER_FORMAT}
                />
                %
              </span>
            </Progress>

            <p>
              <span>Non-Heap Memory</span> (
              <TextFormat
                value={metrics.gauges['jvm.memory.non-heap.used'].value / 1048576}
                type="number"
                format={APP_WHOLE_NUMBER_FORMAT}
              />
              M /{' '}
              <TextFormat
                value={metrics.gauges['jvm.memory.non-heap.committed'].value / 1048576}
                type="number"
                format={APP_WHOLE_NUMBER_FORMAT}
              />
              M)
            </p>
            <Progress
              animated
              min="0"
              max={metrics.gauges['jvm.memory.non-heap.committed'].value}
              value={metrics.gauges['jvm.memory.non-heap.used'].value}
              color="success"
            >
              <span>
                <TextFormat
                  value={(metrics.gauges['jvm.memory.non-heap.used'].value * 100) / metrics.gauges['jvm.memory.non-heap.committed'].value}
                  type="number"
                  format={APP_WHOLE_NUMBER_FORMAT}
                />
                %
              </span>
            </Progress>
          </Col>
          <Col md="4">
            <b>Threads</b> (Total: {metrics.gauges['jvm.threads.count'].value}){' '}
            <Button color="link" className="hand" onClick={this.getThreadDump}>
              <FontAwesomeIcon icon="eye" />
            </Button>
            <p>
              <span>Runnable</span> {metrics.gauges['jvm.threads.runnable.count'].value}
            </p>
            <Progress
              animated
              min="0"
              value={metrics.gauges['jvm.threads.runnable.count'].value}
              max={metrics.gauges['jvm.threads.count'].value}
              color="success"
            >
              <span>
                <TextFormat
                  value={(metrics.gauges['jvm.threads.runnable.count'].value * 100) / metrics.gauges['jvm.threads.count'].value}
                  type="number"
                  format={APP_WHOLE_NUMBER_FORMAT}
                />
                %
              </span>
            </Progress>
            <p>
              <span>Timed Waiting</span> ({metrics.gauges['jvm.threads.timed_waiting.count'].value})
            </p>
            <Progress
              animated
              min="0"
              value={metrics.gauges['jvm.threads.timed_waiting.count'].value}
              max={metrics.gauges['jvm.threads.count'].value}
              color="warning"
            >
              <span>
                <TextFormat
                  value={(metrics.gauges['jvm.threads.timed_waiting.count'].value * 100) / metrics.gauges['jvm.threads.count'].value}
                  type="number"
                  format={APP_WHOLE_NUMBER_FORMAT}
                />
                %
              </span>
            </Progress>
            <p>
              <span>Waiting</span> ({metrics.gauges['jvm.threads.waiting.count'].value})
            </p>
            <Progress
              animated
              min="0"
              value={metrics.gauges['jvm.threads.waiting.count'].value}
              max={metrics.gauges['jvm.threads.count'].value}
              color="warning"
            >
              <span>
                <TextFormat
                  value={(metrics.gauges['jvm.threads.waiting.count'].value * 100) / metrics.gauges['jvm.threads.count'].value}
                  type="number"
                  format={APP_WHOLE_NUMBER_FORMAT}
                />
                %
              </span>
            </Progress>
            <p>
              <span>Blocked</span> ({metrics.gauges['jvm.threads.blocked.count'].value})
            </p>
            <Progress
              animated
              min="0"
              value={metrics.gauges['jvm.threads.blocked.count'].value}
              max={metrics.gauges['jvm.threads.count'].value}
              color="success"
            >
              <span>
                <TextFormat
                  value={(metrics.gauges['jvm.threads.blocked.count'].value * 100) / metrics.gauges['jvm.threads.count'].value}
                  type="number"
                  format={APP_WHOLE_NUMBER_FORMAT}
                />
                %
              </span>
            </Progress>
          </Col>
          <Col md="4">
            <b>Garbage collections</b>
            {this.gaugeRow(metrics, 'Mark Sweep count', 'jvm.garbage.PS-MarkSweep.count')}
            {this.gaugeRow(metrics, 'Mark Sweep time', 'jvm.garbage.PS-MarkSweep.time')}
            {this.gaugeRow(metrics, 'Scavenge count', 'jvm.garbage.PS-Scavenge.count')}
            {this.gaugeRow(metrics, 'Scavenge time', 'jvm.garbage.PS-Scavenge.time')}
          </Col>
        </Row>
      </Col>
    </Row>
  );

  render() {
    const { metrics, isFetching } = this.props;
    const data = metrics || {};
    const { servicesStats, cachesStats } = this.getStats(data);
    return (
      <div>
        <h2 className="metrics-page-heading">Application Metrics</h2>
        <p>
          <Button onClick={this.getMetrics} color={isFetching ? 'btn btn-danger' : 'btn btn-primary'} disabled={isFetching}>
            <FontAwesomeIcon icon="sync" />&nbsp; Refresh
          </Button>
        </p>
        <hr />
        {metrics.gauges ? this.renderGauges(metrics) : ''}

        {metrics.meters && metrics.timers ? (
          <Row>
            <Col sm="12">
              <h3>HTTP requests (events per second)</h3>
              <p>
                <span>Active requests:</span>{' '}
                <b>
                  <TextFormat
                    value={metrics.counters['com.codahale.metrics.servlet.InstrumentedFilter.activeRequests'].count}
                    type="number"
                    format={APP_WHOLE_NUMBER_FORMAT}
                  />
                </b>{' '}
                - <span>Total requests:</span>{' '}
                <b>
                  <TextFormat
                    value={metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count}
                    type="number"
                    format={APP_WHOLE_NUMBER_FORMAT}
                  />
                </b>
              </p>
              <Table>
                <thead>
                  <tr>
                    <th>Code</th>
                    <th>Count</th>
                    <th className="text-right">Mean</th>
                    <th className="text-right">
                      <span>Average</span> (1 min)
                    </th>
                    <th className="text-right">
                      <span>Average</span> (5 min)
                    </th>
                    <th className="text-right">
                      <span>Average</span> (15 min)
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr key={0}>
                    <td>OK</td>
                    <td>
                      <Progress
                        min="0"
                        max={metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count}
                        value={metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].count}
                        color="success"
                        animated
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].mean_rate)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m1_rate)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m5_rate)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m15_rate)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                  </tr>
                  <tr key={1}>
                    <td>Not Found</td>
                    <td>
                      <Progress
                        min="0"
                        max={metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count}
                        value={metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].count}
                        color="success"
                        animated
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(
                          metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].mean_rate
                        )}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(
                          metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m1_rate
                        )}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(
                          metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m5_rate
                        )}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(
                          metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m15_rate
                        )}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                  </tr>
                  <tr key={2}>
                    <td>Server Error</td>
                    <td>
                      <Progress
                        min="0"
                        max={metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count}
                        value={metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].count}
                        color="success"
                        animated
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(
                          metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].mean_rate
                        )}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(
                          metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m1_rate
                        )}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(
                          metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m5_rate
                        )}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(
                          metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m15_rate
                        )}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                  </tr>
                </tbody>
              </Table>
            </Col>
          </Row>
        ) : (
          ''
        )}
        {servicesStats ? (
          <Row>
            <Col sm="12">
              <h3>Services statistics (time in millisecond)</h3>
            </Col>
            <Table>
              <thead>
                <tr>
                  <th>Service name</th>
                  <th>Count</th>
                  <th>Mean</th>
                  <th>Min</th>
                  <th>p50</th>
                  <th>p75</th>
                  <th>p95</th>
                  <th>p99</th>
                  <th>Max</th>
                </tr>
              </thead>
              <tbody>
                {Object.keys(servicesStats).map((key, index) => (
                  <tr key={key}>
                    <td>{key}</td>
                    <td>{servicesStats[key].count}</td>
                    <td>
                      <TextFormat value={servicesStats[key].mean * 1024} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
                    </td>
                    <td>
                      <TextFormat value={servicesStats[key].min * 1024} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
                    </td>
                    <td>
                      <TextFormat value={servicesStats[key].p50 * 1024} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
                    </td>
                    <td>
                      <TextFormat value={servicesStats[key].p75 * 1024} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
                    </td>
                    <td>
                      <TextFormat value={servicesStats[key].p95 * 1024} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
                    </td>
                    <td>
                      <TextFormat value={servicesStats[key].p99 * 1024} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
                    </td>
                    <td>
                      <TextFormat value={servicesStats[key].max * 1024} type="number" format={APP_WHOLE_NUMBER_FORMAT} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </Row>
        ) : (
          ''
        )}

        {cachesStats ? (
          <Row>
            <Col sm="12">
              <h3>Ehcache statistics</h3>
              <Table>
                <thead>
                  <tr>
                    <th>Cache Name</th>
                    <th>Object</th>
                    <th>Misses</th>
                    <th>Eviction Count</th>
                  </tr>
                </thead>
                <tbody>
                  {Object.keys(cachesStats).map((k, v) => (
                    <tr key={k}>
                      <td>{k}</td>
                      <td>{metrics.gauges[`${k}.objects`].value}</td>
                      <td>{metrics.gauges[`${k}.hits`].value}</td>
                      <td>{metrics.gauges[`${k}.misses`].value}</td>
                      <td>{metrics.gauges[`${k}.eviction-count`].value}</td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            </Col>
          </Row>
        ) : (
          ''
        )}

        {metrics.gauges &&
        metrics.gauges['HikariPool-1.pool.TotalConnections'] &&
        metrics.gauges['HikariPool-1.pool.TotalConnections'].value > 0 ? (
          <Row>
            <Col sm="12">
              <h3>DataSource statistics (time in millisecond)</h3>
              <Table>
                <thead>
                  <tr>
                    <th>
                      <span>Usage</span>
                      ({metrics.gauges['HikariPool-1.pool.ActiveConnections'].value} /{' '}
                      {metrics.gauges['HikariPool-1.pool.TotalConnections'].value})
                    </th>
                    <th className="text-right">Count</th>
                    <th className="text-right">Mean</th>
                    <th className="text-right">Min</th>
                    <th className="text-right">p50</th>
                    <th className="text-right">p75</th>
                    <th className="text-right">p95</th>
                    <th className="text-right">p99</th>
                    <th className="text-right">Max</th>
                  </tr>
                </thead>
                <tbody>
                  <tr key="DB">
                    <td>
                      <Progress
                        min="0"
                        max={metrics.gauges['HikariPool-1.pool.TotalConnections'].value}
                        value={metrics.gauges['HikariPool-1.pool.ActiveConnections'].value}
                      >
                        <span>
                          <TextFormat
                            value={
                              (metrics.gauges['HikariPool-1.pool.ActiveConnections'].value * 100) /
                              metrics.gauges['HikariPool-1.pool.TotalConnections'].value
                            }
                            type="number"
                            format={APP_WHOLE_NUMBER_FORMAT}
                          />
                          %
                        </span>
                      </Progress>
                    </td>
                    <td className="text-right">{metrics.histograms['HikariPool-1.pool.Usage'].count}</td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].mean)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].min)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].p50)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].p75)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].p95)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].p99)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                    <td className="text-right">
                      <TextFormat
                        value={this.filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].max)}
                        type="number"
                        format={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
                      />
                    </td>
                  </tr>
                </tbody>
              </Table>
            </Col>
          </Row>
        ) : (
          ''
        )}

        {this.renderModal()}
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  metrics: storeState.administration.metrics,
  isFetching: storeState.administration.loading,
  threadDump: storeState.administration.threadDump
});

const mapDispatchToProps = { systemMetrics, systemThreadDump };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(MetricsPage);

// generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics.component.ts
<%#
 Copyright 2013-2018 the original author or authors from the Simlife project.

 This file is part of the Simlife project, see http://www.simlife.tech/
 for more information.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-%>
import { Component, OnInit } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { <%=simPrefixCapitalized%>MetricsMonitoringModalComponent } from './metrics-modal.component';
import { <%=simPrefixCapitalized%>MetricsService } from './metrics.service';

@Component({
    selector: '<%= simPrefixDashed %>-metrics',
    templateUrl: './metrics.component.html'
})
export class <%=simPrefixCapitalized%>MetricsMonitoringComponent implements OnInit {
    metrics: any = {};
    cachesStats: any = {};
    servicesStats: any = {};
    updatingMetrics = true;
    JCACHE_KEY: string;

    constructor(
        private modalService: NgbModal,
        private metricsService: <%=simPrefixCapitalized%>MetricsService
    ) {
        this.JCACHE_KEY = 'jcache.statistics';
    }

    ngOnInit() {
        this.refresh();
    }

    refresh() {
        this.updatingMetrics = true;
        this.metricsService.getMetrics().subscribe((metrics) => {
            this.metrics = metrics;
            this.updatingMetrics = false;
            this.servicesStats = {};
            this.cachesStats = {};
            Object.keys(metrics.timers).forEach((key) => {
                const value = metrics.timers[key];
                if (key.includes('web.rest') || key.includes('service')) {
                    this.servicesStats[key] = value;
                }
            });
            Object.keys(metrics.gauges).forEach((key) => {
                if (key.includes('jcache.statistics')) {
                    const value = metrics.gauges[key].value;
                    // remove gets or puts
                    const index = key.lastIndexOf('.');
                    const newKey = key.substr(0, index);

                    // Keep the name of the domain
                    this.cachesStats[newKey] = {
                        'name': this.JCACHE_KEY.length,
                        'value': value
                    };
                }
            });
        });
    }

    refreshThreadDumpData() {
        this.metricsService.threadDump().subscribe((data) => {
            const modalRef  = this.modalService.open(<%=simPrefixCapitalized%>MetricsMonitoringModalComponent, { size: 'lg'});
            modalRef.componentInstance.threadDump = data;
            modalRef.result.then((result) => {
                // Left blank intentionally, nothing to do here
            }, (reason) => {
                // Left blank intentionally, nothing to do here
            });
        });
    }

    filterNaN(input) {
        if (isNaN(input)) {
            return 0;
        }
        return input;
    }

}

<%#
 Copyright 2013-2018 the original author or authors from the Simlife project.

 This file is part of the Simlife project, see http://www.simlife.tech/
 for more information.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-%>
<div>
    <h2>
        <span simTranslate="metrics.title">Application Metrics</span>
        <button class="btn btn-primary float-right" (click)="refresh()">
            <span class="fa fa-refresh"></span> <span simTranslate="metrics.refresh.button">Refresh</span>
        </button>
    </h2>

    <h3 simTranslate="metrics.jvm.title">JVM Metrics</h3>
    <div class="row" *ngIf="!updatingMetrics">
        <div class="col-md-4">
            <b simTranslate="metrics.jvm.memory.title">Memory</b>
            <p><span simTranslate="metrics.jvm.memory.total">Total Memory</span> ({{metrics.gauges['jvm.memory.total.used'].value / 1000000 | number:'1.0-0'}}M / {{metrics.gauges['jvm.memory.total.max'].value / 1000000 | number:'1.0-0'}}M)</p>
            <ngb-progressbar type="success" [max]="metrics.gauges['jvm.memory.total.max'].value" [value]="metrics.gauges['jvm.memory.total.used'].value" [striped]="true" [animated]="false">
                <span>{{metrics.gauges['jvm.memory.total.used'].value * 100 / metrics.gauges['jvm.memory.total.max'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span simTranslate="metrics.jvm.memory.heap">Heap Memory</span> ({{metrics.gauges['jvm.memory.heap.used'].value / 1000000 | number:'1.0-0'}}M / {{metrics.gauges['jvm.memory.heap.max'].value / 1000000 | number:'1.0-0'}}M)</p>
            <ngb-progressbar [max]="metrics.gauges['jvm.memory.heap.max'].value" [value]="metrics.gauges['jvm.memory.heap.used'].value" [striped]="true" [animated]="false" type="success">
                <span>{{metrics.gauges['jvm.memory.heap.used'].value * 100 / metrics.gauges['jvm.memory.heap.max'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span simTranslate="metrics.jvm.memory.nonheap">Non-Heap Memory</span> ({{metrics.gauges['jvm.memory.non-heap.used'].value / 1000000 | number:'1.0-0'}}M / {{metrics.gauges['jvm.memory.non-heap.committed'].value / 1000000 | number:'1.0-0'}}M)</p>
            <ngb-progressbar [max]="metrics.gauges['jvm.memory.non-heap.committed'].value" [value]="metrics.gauges['jvm.memory.non-heap.used'].value" [striped]="true" [animated]="false" type="success">
                <span>{{metrics.gauges['jvm.memory.non-heap.used'].value * 100 / metrics.gauges['jvm.memory.non-heap.committed'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
        </div>
        <div class="col-md-4">
            <b simTranslate="metrics.jvm.threads.title">Threads</b> (Total: {{metrics.gauges['jvm.threads.count'].value}}) <a class="hand" (click)="refreshThreadDumpData()" data-toggle="modal" data-target="#threadDump"><i class="fa fa-eye"></i></a>
            <p><span simTranslate="metrics.jvm.threads.runnable">Runnable</span> {{metrics.gauges['jvm.threads.runnable.count'].value}}</p>
            <ngb-progressbar [value]="metrics.gauges['jvm.threads.runnable.count'].value" [max]="metrics.gauges['jvm.threads.count'].value" [striped]="true" [animated]="false" type="success">
                <span>{{metrics.gauges['jvm.threads.runnable.count'].value * 100 / metrics.gauges['jvm.threads.count'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span simTranslate="metrics.jvm.threads.timedwaiting">Timed Waiting</span> ({{metrics.gauges['jvm.threads.timed_waiting.count'].value}})</p>
            <ngb-progressbar [value]="metrics.gauges['jvm.threads.timed_waiting.count'].value" [max]="metrics.gauges['jvm.threads.count'].value" [striped]="true" [animated]="false" type="warning">
                <span>{{metrics.gauges['jvm.threads.timed_waiting.count'].value * 100 / metrics.gauges['jvm.threads.count'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span simTranslate="metrics.jvm.threads.waiting">Waiting</span> ({{metrics.gauges['jvm.threads.waiting.count'].value}})</p>
            <ngb-progressbar [value]="metrics.gauges['jvm.threads.waiting.count'].value" [max]="metrics.gauges['jvm.threads.count'].value" [striped]="true" [animated]="false" type="warning">
                <span>{{metrics.gauges['jvm.threads.waiting.count'].value * 100 / metrics.gauges['jvm.threads.count'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span simTranslate="metrics.jvm.threads.blocked">Blocked</span> ({{metrics.gauges['jvm.threads.blocked.count'].value}})</p>
            <ngb-progressbar [value]="metrics.gauges['jvm.threads.blocked.count'].value" [max]="metrics.gauges['jvm.threads.count'].value" [striped]="true" [animated]="false" type="success">
                <span>{{metrics.gauges['jvm.threads.blocked.count'].value * 100 / metrics.gauges['jvm.threads.count'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
        </div>
        <div class="col-md-4">
            <b simTranslate="metrics.jvm.gc.title">Garbage collections</b>
            <div class="row" *ngIf="metrics.gauges['jvm.garbage.PS-MarkSweep.count']">
                <div class="col-md-9" simTranslate="metrics.jvm.gc.marksweepcount">Mark Sweep count</div>
                <div class="col-md-3 text-right">{{metrics.gauges['jvm.garbage.PS-MarkSweep.count'].value}}</div>
            </div>
            <div class="row" *ngIf="metrics.gauges['jvm.garbage.PS-MarkSweep.time']">
                <div class="col-md-9" simTranslate="metrics.jvm.gc.marksweeptime">Mark Sweep time</div>
                <div class="col-md-3 text-right">{{metrics.gauges['jvm.garbage.PS-MarkSweep.time'].value}}ms</div>
            </div>
            <div class="row" *ngIf="metrics.gauges['jvm.garbage.PS-Scavenge.count']">
                <div class="col-md-9" simTranslate="metrics.jvm.gc.scavengecount">Scavenge count</div>
                <div class="col-md-3 text-right">{{metrics.gauges['jvm.garbage.PS-Scavenge.count'].value}}</div>
            </div>
            <div class="row" *ngIf="metrics.gauges['jvm.garbage.PS-Scavenge.time']">
                <div class="col-md-9" simTranslate="metrics.jvm.gc.scavengetime">Scavenge time</div>
                <div class="col-md-3 text-right">{{metrics.gauges['jvm.garbage.PS-Scavenge.time'].value}}ms</div>
            </div>
        </div>
    </div>
    <div class="well well-lg" *ngIf="updatingMetrics" simTranslate="metrics.updating">Updating...</div>

    <h3 simTranslate="metrics.jvm.http.title">HTTP requests (events per second)</h3>
    <p *ngIf="metrics.counters">
        <span simTranslate="metrics.jvm.http.active">Active requests</span> <b>{{metrics.counters['com.codahale.metrics.servlet.InstrumentedFilter.activeRequests'].count | number:'1.0-0'}}</b> - <span simTranslate="metrics.jvm.http.total">Total requests</span> <b>{{metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count | number:'1.0-0'}}</b>
    </p>
    <div class="table-responsive" *ngIf="!updatingMetrics">
        <table class="table table-striped">
            <thead>
            <tr>
                <th simTranslate="metrics.jvm.http.table.code">Code</th>
                <th simTranslate="metrics.jvm.http.table.count">Count</th>
                <th class="text-right" simTranslate="metrics.jvm.http.table.mean">Mean</th>
                <th class="text-right"><span simTranslate="metrics.jvm.http.table.average">Average</span> (1 min)</th>
                <th class="text-right"><span simTranslate="metrics.jvm.http.table.average">Average</span> (5 min)</th>
                <th class="text-right"><span simTranslate="metrics.jvm.http.table.average">Average</span> (15 min)</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td simTranslate="metrics.jvm.http.code.ok">OK</td>
                <td>
                    <ngb-progressbar [max]="metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count" [value]="metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].count" [striped]="true" [animated]="false" type="success">
                        <span>{{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].count}}</span>
                    </ngb-progressbar>
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].mean_rate) | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m1_rate) | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m5_rate) | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m15_rate) | number:'1.0-2'}}
                </td>
            </tr>
            <tr>
                <td simTranslate="metrics.jvm.http.code.notfound">Not Found</td>
                <td>
                    <ngb-progressbar [max]="metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count" [value]="metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].count" [striped]="true" [animated]="false" type="success">
                        <span>{{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].count}}</span>
                    </ngb-progressbar>
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].mean_rate) | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m1_rate) | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m5_rate) | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m15_rate) | number:'1.0-2'}}
                </td>
            </tr>
            <tr>
                <td simTranslate="metrics.jvm.http.code.servererror">Server error</td>
                <td>
                    <ngb-progressbar [max]="metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count" [value]="metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].count" [striped]="true" [animated]="false" type="success">
                        <span>{{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].count}}</span>
                    </ngb-progressbar>
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].mean_rate) | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m1_rate) | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m5_rate) | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{filterNaN(metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m15_rate) | number:'1.0-2'}}
                </td>
            </tr>
            </tbody>
        </table>
    </div>

    <h3 simTranslate="metrics.servicesstats.title">Services statistics (time in millisecond)</h3>
    <div class="table-responsive" *ngIf="!updatingMetrics">
        <table class="table table-striped">
            <thead>
            <tr>
                <th simTranslate="metrics.servicesstats.table.name">Service name</th>
                <th class="text-right" simTranslate="metrics.servicesstats.table.count">Count</th>
                <th class="text-right" simTranslate="metrics.servicesstats.table.mean">Mean</th>
                <th class="text-right" simTranslate="metrics.servicesstats.table.min">Min</th>
                <th class="text-right" simTranslate="metrics.servicesstats.table.p50">p50</th>
                <th class="text-right" simTranslate="metrics.servicesstats.table.p75">p75</th>
                <th class="text-right" simTranslate="metrics.servicesstats.table.p95">p95</th>
                <th class="text-right" simTranslate="metrics.servicesstats.table.p99">p99</th>
                <th class="text-right" simTranslate="metrics.servicesstats.table.max">Max</th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let entry of servicesStats | keys">
                <td>{{entry.key}}</td>
                <td class="text-right">{{entry.value.count}}</td>
                <td class="text-right">{{entry.value.mean * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.min * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.p50 * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.p75 * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.p95 * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.p99 * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.max * 1000 | number:'1.0-0'}}</td>
            </tr>
            </tbody>
        </table>
    </div>
<% if (['ehcache', 'infinispan'].includes(cacheProvider)) { %>
    <h3 simTranslate="metrics.cache.title">Cache statistics</h3>
    <div class="table-responsive" *ngIf="!updatingMetrics">
        <table class="table table-striped">
            <thead>
            <tr>
                <th simTranslate="metrics.cache.cachename">Cache name</th>
                <th class="text-right" data-translate="metrics.cache.hits">Cache Hits</th>
                <th class="text-right" data-translate="metrics.cache.misses">Cache Misses</th>
                <th class="text-right" data-translate="metrics.cache.gets">Cache Gets</th>
                <th class="text-right" data-translate="metrics.cache.puts">Cache Puts</th>
                <th class="text-right" data-translate="metrics.cache.removals">Cache Removals</th>
                <th class="text-right" data-translate="metrics.cache.evictions">Cache Evictions</th>
                <th class="text-right" data-translate="metrics.cache.hitPercent">Cache Hit %</th>
                <th class="text-right" data-translate="metrics.cache.missPercent">Cache Miss %</th>
                <th class="text-right" data-translate="metrics.cache.averageGetTime">Average get time (µs)</th>
                <th class="text-right" data-translate="metrics.cache.averagePutTime">Average put time (µs)</th>
                <th class="text-right" data-translate="metrics.cache.averageRemoveTime">Average remove time (µs)</th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let entry of cachesStats | keys">
                <td>{{entry.key}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.cache-hits'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.cache-misses'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.cache-gets'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.cache-puts'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.cache-removals'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.cache-evictions'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.cache-hit-percentage'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.cache-miss-percentage'].value }}</td>
                <td class="text-right">{{filterNaN(metrics.gauges[entry.key + '.average-get-time'].value)  | number : '1.2-2' }}</td>
                <td class="text-right">{{filterNaN(metrics.gauges[entry.key + '.average-put-time'].value)  | number : '1.2-2'}}</td>
                <td class="text-right">{{filterNaN(metrics.gauges[entry.key + '.average-remove-time'].value) | number : '1.2-2' }}</td>
            </tr>
            </tbody>
        </table>
    </div>
<%_ } _%>
    <h3 simTranslate="metrics.datasource.title" *ngIf="metrics.gauges && metrics.gauges['HikariPool-1.pool.TotalConnections'] && metrics.gauges['HikariPool-1.pool.TotalConnections'].value > 0">DataSource statistics (time in millisecond)</h3>
    <div class="table-responsive" *ngIf="!updatingMetrics && metrics.gauges && metrics.gauges['HikariPool-1.pool.TotalConnections'] && metrics.gauges['HikariPool-1.pool.TotalConnections'].value > 0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th><span simTranslate="metrics.datasource.usage">Usage</span> ({{metrics.gauges['HikariPool-1.pool.ActiveConnections'].value}} / {{metrics.gauges['HikariPool-1.pool.TotalConnections'].value}})</th>
                    <th class="text-right" simTranslate="metrics.datasource.count">Count</th>
                    <th class="text-right" simTranslate="metrics.datasource.mean">Mean</th>
                    <th class="text-right" simTranslate="metrics.datasource.min">Min</th>
                    <th class="text-right" simTranslate="metrics.datasource.p50">p50</th>
                    <th class="text-right" simTranslate="metrics.datasource.p75">p75</th>
                    <th class="text-right" simTranslate="metrics.datasource.p95">p95</th>
                    <th class="text-right" simTranslate="metrics.datasource.p99">p99</th>
                    <th class="text-right" simTranslate="metrics.datasource.max">Max</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div class="progress progress-striped">
                            <ngb-progressbar [max]="metrics.gauges['HikariPool-1.pool.TotalConnections'].value" [value]="metrics.gauges['HikariPool-1.pool.ActiveConnections'].value" [striped]="true" [animated]="false" type="success">
                                <span>{{metrics.gauges['HikariPool-1.pool.ActiveConnections'].value * 100 / metrics.gauges['HikariPool-1.pool.TotalConnections'].value  | number:'1.0-0'}}%</span>
                            </ngb-progressbar>
                        </div>
                    </td>
                    <td class="text-right">{{metrics.histograms['HikariPool-1.pool.Usage'].count}}</td>
                    <td class="text-right">{{filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].mean) | number:'1.0-2'}}</td>
                    <td class="text-right">{{filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].min) | number:'1.0-2'}}</td>
                    <td class="text-right">{{filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].p50) | number:'1.0-2'}}</td>
                    <td class="text-right">{{filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].p75) | number:'1.0-2'}}</td>
                    <td class="text-right">{{filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].p95) | number:'1.0-2'}}</td>
                    <td class="text-right">{{filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].p99) | number:'1.0-2'}}</td>
                    <td class="text-right">{{filterNaN(metrics.histograms['HikariPool-1.pool.Usage'].max) | number:'1.0-2'}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
